name: FitLife Backend CI

on:
  push:
    branches:
      - '**'        # Ejecuta en cualquier rama
  pull_request:
    branches:
      - '**'        # Tambi√©n en PR desde cualquier rama

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run Black
        run: black --check src tests

      - name: Run Flake8
        run: flake8 src tests

      - name: Run Mypy
        run: mypy src

      - name: Run Tests with Coverage
        run: pytest --cov=src --cov-report=term